### ISSUE TITLE
Feature Request: Starting an external task manager

### ISSUE THREAD

**Issue by tobimensch** [jmechnich/sysstat-applet#2] opened 2020-07-03 20:43 UTC
It would be nice, if this applet could start an external task manager
(which one should be configurable).

**Comment by jmechnich** [comment] 2020-07-06 17:38
Hello there,

this sounds like a pretty good idea!

An external command can now be configured individually for each of the three icons via right click menu (changes inside the options dialog have to be confirmed by pressing Enter) and triggered by middle clicking them.

A few suggestions:
- ``xosview``
- ``terminator -e "htop"`` (start is quite slow because of terminator)
- ``xterm -e "htop"`` (starts faster but looks ugly)

In general, commands like ``vmstat 1``, ``iostat 1``, etc. could be useful. ``fatrace`` might be an interesting alternative as well but requires some additional work in order to be able to run as root (maybe use ``gksudo`` or set up a dedicated ``sudo`` rule without requiring a password).

Let me know if you are running into any trouble.

Cheers,
Jörg

**Comment by tobimensch** [comment] 2020-07-07 14:12
Thansk @jmechnich.

This issue is blocking the command execution from working on my system:

https://github.com/jmechnich/sysstat-applet/issues/10

**Comment by jmechnich** [comment] 2022-07-27 09:19
Closing with #10

**Closed as completed by jmechnich** 2022-07-27 09:19 UTC
Labels: enhancement
